# Generated by Django 4.0.2 on 2022-02-20 21:12

from django.db import migrations, models
import markupfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='_body_mu_rendered',
            field=models.TextField(default=None, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='body_mu',
            field=markupfield.fields.MarkupField(blank=True, rendered_field=True),
        ),
        migrations.AddField(
            model_name='post',
            name='body_mu_markup_type',
            field=models.CharField(blank=True, choices=[('', '--'), ('html', 'HTML'), ('plain', 'Plain')], default=None, max_length=30, null=True),
        ),
    ]
