# Generated by Django 4.0.2 on 2022-02-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_post__body_mu_rendered_post_body_mu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='_body_mu_rendered',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_mu',
        ),
        migrations.RemoveField(
            model_name='post',
            name='body_mu_markup_type',
        ),
    ]
